name: junit tests
on: [push, pull_request, pull_request_review]
jobs:
  run_junit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'openjdk'

      - name: grant permissions to gradlew
        run: chmod +x gradlew

      - name: Test
        run: gradle test --tests "*"

      - name: Test Success
        if: success()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const pull_number = "${{ github.event.number }}"
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "All tests passed.",
              event: "APPROVE"
            })
      - name: Test Fail
        if: failure()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const pull_number = "${{ github.event.number }}"
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "There is something wrong with test code.",
              event: "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pull_number,
              state: "closed"
            })

